#  T-tests and P-values

In statistics, t-test is used to test if two data samples have a significant difference between their means. There are two types of t-test:

* **Student's t-test** (a.k.a. independent or uncorrelated t-test). This type of t-test is to compare the samples of **two independent populations** (e.g. test scores of students in two different classes). `scipy` provides the [`ttest_ind`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_ind.html) method to conduct student's t-test.

* **Paired t-test** (a.k.a. dependent or correlated t-test). This type of t-test is to compare the samples of **the same population** (e.g. scores of different tests of students in the same class). `scipy` provides the [`ttest_rel`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_rel.html) method to conduct paired t-test.

Both types of t-tests return a number which is called the **p-value**. If p-value is below 0.05, we can confidently declare the null-hypothesis is rejected and the difference is significant. If p-value is between 0.05 and 0.1, we may also declare the null-hypothesis is rejected but we are not highly confident. If p-value is above 0.1 we do not reject the null-hypothesis.

Read more about the t-test in [this article](http://b.link/test50) and [this Quora](http://b.link/unpaired97). Make sure you understand when to use which type of t-test.

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import seaborn as sns

### One tailed t-test 
In a packing plant, a machine packs cartons with jars. It is supposed that a new machine will pack faster on the average than the machine currently used. To test that hypothesis, the times it takes each machine to pack ten cartons are recorded. The results, in seconds, are shown in the tables in the file files_for_lab/ttest_machine.xlsx. Assume that there is sufficient evidence to conduct the t test, does the data provide sufficient evidence to show if one machine is better than the other?

#### Import dataset

In [3]:
# Your code here:

In [4]:
machine = pd.read_csv('ttest_machine.txt',delimiter=' ')
machine

   New_machine  Old_machine
0         42.1         42.7
1         41.0         43.6
2         41.3         43.8
3         41.8         43.3
4         42.4         42.5
5         42.8         43.5
6         43.2         43.1
7         42.3         41.7
8         41.8         44.0
9         42.7         44.1

In [5]:
# H0 = two machines are not different 
# H1 = one machine is better than the other one

st.ttest_ind(machine['New_machine'], machine['Old_machine'], equal_var=False)

Ttest_indResult(statistic=-3.3972307061176026, pvalue=0.00324224946631798)

In [6]:
# negative stat indicates the new machine is significantly more efficient than the old one.

#### Import dataset

In this challenge we will work on the Pokemon dataset you have already used. The goal is to test whether different groups of pokemon (e.g. Legendary vs Normal, Generation 1 vs 2, single-type vs dual-type) have different stats (e.g. HP, Attack, Defense, etc.). Use pokemon.csv

In [7]:
# Your code here:
pokemon = pd.read_csv('pokemon.txt', delimiter=',')
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [8]:
pokemon.drop('#', axis=1, inplace=True)
pokemon.head()

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [9]:
# cleaning up the name column
def cleanup(x):
    if 'Mega' in x['Name']:
        return 'Mega' + x['Name'].partition('Mega')[2]
    else:
        return x['Name']

pokemon['Name'] = pokemon.apply(cleanup, axis=1)

# test transformed data
pokemon.head(10)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [25]:
long_names = pokemon[pokemon['Name'].str.len()>16]
long_names

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
422,KyogrePrimal Kyogre,Water,NaN,770,100,150,90,180,160,90,3,True
424,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
428,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True
429,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True
430,DeoxysDefense Forme,Psychic,NaN,600,50,70,160,70,160,90,3,True
431,DeoxysSpeed Forme,Psychic,NaN,600,50,95,90,95,90,180,3,True
458,WormadamPlant Cloak,Bug,Grass,424,60,59,85,79,105,36,4,False
459,WormadamSandy Cloak,Bug,Ground,424,60,79,105,59,85,36,4,False
460,WormadamTrash Cloak,Bug,Steel,424,60,69,95,69,95,36,4,False
544,GiratinaAltered Forme,Ghost,Dragon,680,150,100,120,100,120,90,4,True
545,GiratinaOrigin Forme,Ghost,Dragon,680,150,120,100,120,100,90,4,True
550,ShayminLand Forme,Grass,NaN,600,100,100,100,100,100,100,4,True
615,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
616,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False
702,TornadusIncarnate Forme,Flying,NaN,580,79,115,70,125,80,111,5,True
703,TornadusTherian Forme,Flying,NaN,580,79,100,80,110,90,121,5,True
704,ThundurusIncarnate Forme,Electric,Flying,580,79,115,70,125,80,111,5,True
705,ThundurusTherian Forme,Electric,Flying,580,79,105,70,145,80,101,5,True
708,LandorusIncarnate Forme,Ground,Flying,600,89,125,90,115,80,101,5,True
709,LandorusTherian Forme,Ground,Flying,600,89,145,90,105,80,91,5,True
711,KyuremBlack Kyurem,Dragon,Ice,700,125,170,100,120,90,95,5,True
712,KyuremWhite Kyurem,Dragon,Ice,700,125,120,90,170,100,95,5,True
713,KeldeoOrdinary Forme,Water,Fighting,580,91,72,90,129,90,108,5,False
714,KeldeoResolute Forme,Water,Fighting,580,91,72,90,129,90,108,5,False
715,MeloettaAria Forme,Normal,Psychic,600,100,77,77,128,128,90,5,False
716,MeloettaPirouette Forme,Normal,Fighting,600,100,128,90,77,77,128,5,False
750,AegislashBlade Forme,Steel,Ghost,520,60,150,50,150,50,60,6,False
751,AegislashShield Forme,Steel,Ghost,520,60,50,150,50,150,60,6,False
780,PumpkabooAverage Size,Ghost,Grass,335,49,66,70,44,55,51,6,False
781,PumpkabooSmall Size,Ghost,Grass,335,44,66,70,44,55,56,6,False
782,PumpkabooLarge Size,Ghost,Grass,335,54,66,70,44,55,46,6,False
783,PumpkabooSuper Size,Ghost,Grass,335,59,66,70,44,55,41,6,False
784,GourgeistAverage Size,Ghost,Grass,494,65,90,122,58,75,84,6,False
785,GourgeistSmall Size,Ghost,Grass,494,55,85,122,58,75,99,6,False
786,GourgeistLarge Size,Ghost,Grass,494,75,95,122,58,75,69,6,False
787,GourgeistSuper Size,Ghost,Grass,494,85,100,122,58,75,54,6,False
797,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

In [12]:
pokemon.to_csv('pokemon.csv', index=False)

#### First we want to define a function with which we can test the means of a feature set of two samples. 

In the next cell you'll see the annotations of the Python function that explains what this function does and its arguments and returned value. This type of annotation is called **docstring** which is a convention used among Python developers. The docstring convention allows developers to write consistent tech documentations for their codes so that others can read. It also allows some websites to automatically parse the docstrings and display user-friendly documentations.

Follow the specifications of the docstring and complete the function.

#### Using the `t_test_features` function, conduct t-test for Lengendary vs non-Legendary pokemons.

*Hint: your output should look like below:*

```
{'HP': 1.0026911708035284e-13,
 'Attack': 2.520372449236646e-16,
 'Defense': 4.8269984949193316e-11,
 'Sp. Atk': 1.5514614112239812e-21,
 'Sp. Def': 2.2949327864052826e-15,
 'Speed': 1.049016311882451e-18,
 'Total': 9.357954335957446e-47}
 ```

In [30]:
def t_test_features(s1, s2, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']):
    """Test means of a feature set of two samples
    
    Args:
        s1 (dataframe): sample 1
        s2 (dataframe): sample 2
        features (list): an array of features to test
    
    Returns:
        dict: a dictionary of t-test scores for each feature where the feature name is the key and the p-value is the value
    """
    results = {}

    # Your code here
    s1 = pokemon[pokemon['Legendary']==True]
    s2 = pokemon[pokemon['Legendary']==False]
    for i in features:
        p = st.ttest_ind(s1[i], s2[i], equal_var=False)
        results[i] = p[1]
    
    return results

In [31]:
t_test_features(s1, s2, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total'])

{'HP': 1.0026911708035284e-13,
 'Attack': 2.520372449236646e-16,
 'Defense': 4.8269984949193316e-11,
 'Sp. Atk': 1.5514614112239812e-21,
 'Sp. Def': 2.2949327864052826e-15,
 'Speed': 1.049016311882451e-18,
 'Total': 9.357954335957446e-47}

From the test results above, what conclusion can you make? Do Legendary and non-Legendary pokemons have significantly different stats on each feature?

In [35]:
# H0: these two groups are not significantly different
# H1: these two groups are significantly different
# All p-values are close to 0 which means we reject H0 and prove that these two groups of pokemons are very different.

#### Next, conduct t-test for Generation 1 and Generation 2 pokemons.

In [36]:
# Your code here
results = {}
features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']

# Your code here
g1 = pokemon[pokemon['Generation']==1]
g2 = pokemon[pokemon['Generation']==2]
for i in features:
    p_generation = st.ttest_ind(g1[i], g2[i], equal_var=False)
    results[i] = p_generation[1]

print(results)

{'HP': 0.14551697834219623, 'Attack': 0.24721958967217725, 'Defense': 0.5677711011725426, 'Sp. Atk': 0.12332165977104388, 'Sp. Def': 0.18829872292645752, 'Speed': 0.00239265937312135, 'Total': 0.5631377907941676}

#### What conclusions can you make?

In [ ]:
# There is no significant difference between generation 1 and 2.

#### Compare pokemons who have single type vs those having two types.

In [37]:
# Your code here
results = {}
features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']

# Your code here
t1 = pokemon[pokemon['Type 2'].isna()==True]
t2 = pokemon[pokemon['Type 2'].isna()==False]
for i in features:
    p_types = st.ttest_ind(t1[i], t2[i], equal_var=False)
    results[i] = p_types[1]

print(results)

{'HP': 0.11314389855379414, 'Attack': 0.00014932578145948305, 'Defense': 2.7978540411514693e-08, 'Sp. Atk': 0.00013876216585667907, 'Sp. Def': 0.00010730610934512779, 'Speed': 0.02421703281819093, 'Total': 1.1157056505229961e-07}

#### What conclusions can you make?

In [38]:
# Your comment here
# Pokemons with 2 types are different from those with a single type in all features except for HP.

#### Now, we want to compare whether there are significant differences of `Attack` vs `Defense`  and  `Sp. Atk` vs `Sp. Def` of all pokemons. Please write your code below.

*Hint: are you comparing different populations or the same population?*

In [39]:
# Your code here

st.ttest_rel(pokemon['Attack'], pokemon['Defense'])

TtestResult(statistic=4.325566393330478, pvalue=1.7140303479358558e-05, df=799)

In [41]:
# Attack and Defense are significantly different

In [40]:
st.ttest_rel(pokemon['Sp. Atk'], pokemon['Sp. Def'])

TtestResult(statistic=0.853986188453353, pvalue=0.3933685997548122, df=799)

In [43]:
# Sp. Atk and Sp. Def are not significantly different

#### What conclusions can you make?

In [ ]:
# Your comment here